# Generated by Django 5.2.9 on 2026-02-15 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('agency', 'Agency')], default='free', max_length=50)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_url', models.CharField(blank=True, max_length=500, null=True)),
                ('telegram_url', models.CharField(blank=True, max_length=500, null=True)),
                ('audit_type', models.CharField(default='standard', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('collected_data_json', models.JSONField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='bot.user')),
            ],
        ),
    ]
